### ISSUE TITLE
error while starting the bot

### ISSUE THREAD

**Issue by fakesmile9704** [armintum/Bard-Discord-bot#14]
```
@bot.hybrid_command(name="toggledm", description="Toggle DM for chatting.")
AttributeError: 'Bot' object has no attribute 'hybrid_command'
```
followed all the steps correctly but getting this error

**Comment by MrAlaminH** [comment]
The error message means that the hybrid_command attribute does not exist on the Bot object. This is because the hybrid_command decorator was introduced in a newer version of the discord.py library than the version you are using.

To solve this error, you need to update your discord.py library to a newer version. You can do this by running the following command in your terminal:  pip install -U discord.py
